In [ ]:
import pandas as pd
import sqlite3

# Load CSV dataset
df = pd.read_csv("hotel_bookings.csv")

# Create/connect SQLite database
conn = sqlite3.connect("hotel_booking.db")

# Store dataframe into SQL table
df.to_sql("hotel_bookings", conn, if_exists="replace", index=False)

print("Database and table created successfully!")

Database and table created successfully!

In [ ]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

pd.read_sql(query, conn)

             name
0  hotel_bookings

Total Bookings

In [ ]:
query = """
SELECT COUNT(*) AS total_bookings
FROM hotel_bookings
"""

pd.read_sql(query, conn)

   total_bookings
0          119390